CREATE TABLE `pessoa` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(50) NOT NULL,
  `SEXO` enum('M','F','Outro') NOT NULL,
  `DATA_NASCIMENTO` date DEFAULT NULL,
  `NOME_GENITOR` varchar(50) DEFAULT NULL,
  `NOME_GENITORA` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci


CREATE TABLE `registro` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `TERMO` int NOT NULL,
  `LIVRO` varchar(10) NOT NULL,
  `FOLHA` int NOT NULL,
  `DATA_REGISTRO` date DEFAULT NULL,
  `Id_PESSOA` int DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `FK_PESSOA_REGISTRO` (`Id_PESSOA`),
  CONSTRAINT `FK_PESSOA_REGISTRO` FOREIGN KEY (`Id_PESSOA`) REFERENCES `pessoa` (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci